units:
  kx: cx
  ky: cy
  padding: 0.4
  px: kx+padding
  py: ky+padding
  mcu_height: 34
  mcu_width: 18
  # distance keys to mcu
  mcu_padding: 1.5
  scrollwheel_width: 17
  scrollwheel_height: 14
  screw_diameter: 4.7
  screw_hole: 4.1
  screen_screw_diameter: 4
  screen_screw_hole: 2.2
  switchplate_switch_cutout: 14
  switchplate_scrollwheel_cutout_x: 17.5
  switchplate_scrollwheel_cutout_y: 14.5
  switchplate_screw_diameter: 3.3
  switchplate_screw_hole: 2.2
  thumb_radius: 65
points:
  zones:
    # The primary 6x4 key matrix, plus 3 modifiers.
    matrix:
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer2:
          rows.mod.skip: true
          rows.num.skip: true
        outer1:
          rows.mod.skip: true
          rows.num.skip: true
        pinky:
          # for pinky(and the two rows above, home position is actually the bottom row and the "num" row here is an extra row for ring finger)
        ring:
          key.stagger: 15 - ky
        middle:
          key.stagger: 4
        index:
          key.stagger: -7
        inner:
          rows.mod.skip: true
          key.stagger: -3
      rows:
        # Four main rows, one partial row.
        mod:
        bottom:
        home:
        top:
        num:
    # Thumb cluster for Layer and Space keys.
    thumb_center:
      key.skip: true
      anchor:
        ref: matrix_index_home
        shift: [3, -95]


    thumbfan_inner:
      # Choc spacing
      key:
        padding: 1px
        spread: 1.2ky
        splay: -24
        stagger: -6
        rotate: 90
      # Place thumbs where the inner mod would go.
      anchor:
        ref: matrix_inner_mod
        shift: [1.2, 2.5]

    thumbfan_home:
      anchor:
        ref: thumb_center
        orient: 56
        shift: [thumb_radius, 0]
        rotate: 10

    thumbfan_outer:
      anchor:
        ref: thumb_center
        orient: 38
        shift: [thumb_radius, 0]
        rotate: 10
    thumbfanfar:
      anchor:
        ref: thumb_center
        orient: 20
        shift: [thumb_radius, 0]
        rotate: 10

